# Generated by Django 3.2.9 on 2021-11-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModelForSwaggerFilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='This has to be the primarykey (ex.: username) you difined in your table!', max_length=255)),
                ('field', models.CharField(help_text='The field you want to retrive of your table.', max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', models.CharField(help_text='Primary key.', max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('fullname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('cep', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('user', models.OneToOneField(help_text='Primary key.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration_app.user')),
            ],
            options={
                'db_table': 'adress',
            },
        ),
    ]
