# Generated by Django 3.2.9 on 2021-11-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('fullname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('cep', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.user')),
            ],
            options={
                'db_table': 'adress',
            },
        ),
    ]
